{% set version = "91.5.0esr" %}

package:
  name: firefox
  version: {{ version }}

source:
  url: https://ftp.mozilla.org/pub/firefox/releases/{{ version }}/linux-x86_64/en-US/firefox-{{ version }}.tar.bz2  # [linux64]
  sha256: 69147d3d71864dfa7932a52a12b19b9f484ba6762f263bf65da54fc9699789a6  # [linux64]

  fn: firefox.pkg  # [osx]
  url: https://ftp.mozilla.org/pub/firefox/releases/{{ version }}/mac/en-US/Firefox%20{{ version }}.pkg  # [osx]
  sha256: 5352e941a30732346b33deccb038e1953f39dcd0a23b7a2c74a59f992f41e892  # [osx]

  fn: firefox.msi  # [win]
  url: https://ftp.mozilla.org/pub/firefox/releases/{{ version }}/win64/en-US/Firefox%20Setup%20{{ version }}.msi  # [win]
  sha256: d744b6e1e56f84134c3d682c0e6a79ba2f15e065b9f8c2bb23fa0f9f009d189a  # [win]

build:
  number: 0
  binary_relocation:
    - bin/firefox

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - sysroot_linux-64 2.17  # [linux64]

test:
  requires:
    - geckodriver
    - pytest
    - python >=3.6
    - selenium
  commands:
    - copy {{ RECIPE_DIR }}\test_selenium.py .  # [win]
    - copy {{ RECIPE_DIR }}\setup.cfg .  # [win]
    - cp {{ RECIPE_DIR }}/test_selenium.py {{ RECIPE_DIR }}/setup.cfg .  # [not win]
    # TODO: may be needed in the future
    # https://firefox-source-docs.mozilla.org/testing/geckodriver/Notarization.html
    # - set -m && % xattr -r -d com.apple.quarantine $PREFIX/bin/geckodriver  # [osx]
    - python -m pytest
  downstreams:
    - geckodriver

about:
  home: https://www.mozilla.org/en-US/firefox/releases
  license: MPL-2.0
  license_family: MOZILLA
  license_file: LICENSE
  summary: Firefox web browser

extra:
  recipe-maintainers:
    - birdsarah
    - ocefpaf
    - bollwyvl
