{% set version = "128.4.0esr" %}

package:
  name: firefox
  version: {{ version }}

source:
  folder: firefox  # [linux64]
  url: https://ftp.mozilla.org/pub/firefox/releases/{{ version }}/linux-x86_64/en-US/firefox-{{ version }}.tar.bz2  # [linux64]
  sha256: d84cdd480de7f6f4bffb4342f974581b9e5c0e24f1179038b8119d9b3d1b1e4f  # [linux64]

  fn: firefox.pkg  # [osx]
  url: https://ftp.mozilla.org/pub/firefox/releases/{{ version }}/mac/en-US/Firefox%20{{ version }}.pkg  # [osx]
  sha256: d21fe0af7aa88792820a32d67c7465b630cec45815d28fb21abe0f83308b2982  # [osx]

  fn: firefox.msi  # [win]
  url: https://ftp.mozilla.org/pub/firefox/releases/{{ version }}/win64/en-US/Firefox%20Setup%20{{ version }}.msi  # [win]
  sha256: 39caf1a519d129719166853e090dcb8169c5848fd29a2bc16f18ecc3ee192f1a  # [win]

build:
  number: 0
  binary_relocation:
    - bin/firefox
  script_env:
    - MOZ_HEADLESS=1

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}

test:
  requires:
    - geckodriver
    - pytest
    - python >=3.6
    - selenium >=4
  commands:
    - copy {{ RECIPE_DIR }}\test_selenium.py .  # [win]
    - copy {{ RECIPE_DIR }}\setup.cfg .  # [win]
    - cp {{ RECIPE_DIR }}/test_selenium.py {{ RECIPE_DIR }}/setup.cfg .  # [not win]
    - firefox --version
    - firefox --help
    # TODO: may be needed in the future
    # https://firefox-source-docs.mozilla.org/testing/geckodriver/Notarization.html
    # - set -m && % xattr -r -d com.apple.quarantine $PREFIX/bin/geckodriver  # [osx]
    - python -m pytest test_selenium.py

about:
  home: https://www.mozilla.org/en-US/firefox/releases
  license: MPL-2.0
  license_family: MOZILLA
  license_file: LICENSE
  summary: Firefox web browser

extra:
  recipe-maintainers:
    - birdsarah
    - ocefpaf
    - bollwyvl
