{% set version = "102.15.0esr" %}

package:
  name: firefox
  version: {{ version }}

source:
  folder: firefox  # [linux64]
  url: https://ftp.mozilla.org/pub/firefox/releases/{{ version }}/linux-x86_64/en-US/firefox-{{ version }}.tar.bz2  # [linux64]
  sha256: 4f9a5ac02b463bf90ee55cddb08b9661987e406213abc5ae12d06c222b874cc8  # [linux64]

  fn: firefox.pkg  # [osx]
  url: https://ftp.mozilla.org/pub/firefox/releases/{{ version }}/mac/en-US/Firefox%20{{ version }}.pkg  # [osx]
  sha256: 3a4bc6f3a6d08820b2f65792eb2eb8a6ba3ccbd28fb350adcecb68be7fddcbcd  # [osx]

  fn: firefox.msi  # [win]
  url: https://ftp.mozilla.org/pub/firefox/releases/{{ version }}/win64/en-US/Firefox%20Setup%20{{ version }}.msi  # [win]
  sha256: 09178271da9c67b2ca3e2e04271c8b74a4dc5f0d55c6487db281448e5446b3fa  # [win]

build:
  number: 0
  binary_relocation:
    - bin/firefox
  script_env:
    - MOZ_HEADLESS=1

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - sysroot_linux-64 2.17  # [linux64]

test:
  requires:
    - geckodriver
    - pytest
    - python >=3.6
    - selenium >=4
  commands:
    - copy {{ RECIPE_DIR }}\test_selenium.py .  # [win]
    - copy {{ RECIPE_DIR }}\setup.cfg .  # [win]
    - cp {{ RECIPE_DIR }}/test_selenium.py {{ RECIPE_DIR }}/setup.cfg .  # [not win]
    - firefox --version
    - firefox --help
    # TODO: may be needed in the future
    # https://firefox-source-docs.mozilla.org/testing/geckodriver/Notarization.html
    # - set -m && % xattr -r -d com.apple.quarantine $PREFIX/bin/geckodriver  # [osx]
    - python -m pytest test_selenium.py

about:
  home: https://www.mozilla.org/en-US/firefox/releases
  license: MPL-2.0
  license_family: MOZILLA
  license_file: LICENSE
  summary: Firefox web browser

extra:
  recipe-maintainers:
    - birdsarah
    - ocefpaf
    - bollwyvl
