{% set version = "114.0" %}

package:
  name: firefox
  version: {{ version }}

source:
  folder: firefox  # [linux64]
  url: https://ftp.mozilla.org/pub/firefox/releases/{{ version }}/linux-x86_64/en-US/firefox-{{ version }}.tar.bz2  # [linux64]
  sha256: ac4c315bcfacf844a249ac1298536b6471dd5c65b16cc623b326db0af9376df6  # [linux64]

  fn: firefox.pkg  # [osx]
  url: https://ftp.mozilla.org/pub/firefox/releases/{{ version }}/mac/en-US/Firefox%20{{ version }}.pkg  # [osx]
  sha256: 5a967d1dae2d0038be406a3232f018750742bb7e68079359db8993cf865fd07b  # [osx]

  fn: firefox.msi  # [win]
  url: https://ftp.mozilla.org/pub/firefox/releases/{{ version }}/win64/en-US/Firefox%20Setup%20{{ version }}.msi  # [win]
  sha256: 4d74d3337be745b9add6b760725c56768024ac5d0f5f2432f1c14585b1a09311  # [win]

build:
  number: 0
  binary_relocation:
    - bin/firefox
  script_env:
    - MOZ_HEADLESS=1

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - sysroot_linux-64 2.17  # [linux64]

test:
  requires:
    - geckodriver
    - pytest
    - python >=3.6
    - selenium >=4
  commands:
    - copy {{ RECIPE_DIR }}\test_selenium.py .  # [win]
    - copy {{ RECIPE_DIR }}\setup.cfg .  # [win]
    - cp {{ RECIPE_DIR }}/test_selenium.py {{ RECIPE_DIR }}/setup.cfg .  # [not win]
    - firefox --version
    - firefox --help
    # TODO: may be needed in the future
    # https://firefox-source-docs.mozilla.org/testing/geckodriver/Notarization.html
    # - set -m && % xattr -r -d com.apple.quarantine $PREFIX/bin/geckodriver  # [osx]
    - python -m pytest test_selenium.py

about:
  home: https://www.mozilla.org/en-US/firefox/releases
  license: MPL-2.0
  license_family: MOZILLA
  license_file: LICENSE
  summary: Firefox web browser

extra:
  recipe-maintainers:
    - birdsarah
    - ocefpaf
    - bollwyvl
