{% set version = "94.0.1" %}

package:
  name: firefox
  version: {{ version }}

source:
  url: https://ftp.mozilla.org/pub/firefox/releases/{{ version }}/linux-x86_64/en-US/firefox-{{ version }}.tar.bz2  # [linux64]
  sha256: f40c7f084478f225a9611a971d71f5f59e63db7b9e9a42c95a2b7ad83c8a5b83  # [linux64]

  fn: firefox.pkg  # [osx]
  url: https://ftp.mozilla.org/pub/firefox/releases/{{ version }}/mac/en-US/Firefox%20{{ version }}.pkg  # [osx]
  sha256: 39a4c3fc26c8911aa4733b825676d3a73a7a1de9752f3617b67f18747ca55420  # [osx]

  fn: firefox.msi  # [win]
  url: https://ftp.mozilla.org/pub/firefox/releases/{{ version }}/win64/en-US/Firefox%20Setup%20{{ version }}.msi  # [win]
  sha256: a29c3cdcad860123c3b71f75798237d1e83f659ca8834c4fca2b5708246b58c5  # [win]

build:
  number: 0
  binary_relocation:
    - bin/firefox

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - sysroot_linux-64 2.17  # [linux64]

test:
  requires:
    - geckodriver
    - pytest
    - python >=3.6
    - selenium
  commands:
    - copy {{ RECIPE_DIR }}\test_selenium.py .  # [win]
    - copy {{ RECIPE_DIR }}\setup.cfg .  # [win]
    - cp {{ RECIPE_DIR }}/test_selenium.py {{ RECIPE_DIR }}/setup.cfg .  # [not win]
    # TODO: may be needed in the future
    # https://firefox-source-docs.mozilla.org/testing/geckodriver/Notarization.html
    # - set -m && % xattr -r -d com.apple.quarantine $PREFIX/bin/geckodriver  # [osx]
    - python -m pytest


about:
  home: https://www.mozilla.org/en-US/firefox/releases
  license: MPL-2.0
  license_family: MOZILLA
  license_file: LICENSE
  summary: Firefox web browser

extra:
  recipe-maintainers:
    - birdsarah
    - ocefpaf
    - bollwyvl
