# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: "148.0.2"

package:
  name: firefox
  version: ${{ version }}

source:
  - if: linux and x86_64
    then:
      url: https://ftp.mozilla.org/pub/firefox/releases/${{ version }}/linux-x86_64/en-US/firefox-${{ version }}.tar.xz
      sha256: e15afd77dab1ba3c1806b4436cd603b35ea1d4e06a452b5c572ef7bc1663d75a
      target_directory: firefox
  - if: osx
    then:
      url: https://ftp.mozilla.org/pub/firefox/releases/${{ version }}/mac/en-US/Firefox%20${{ version }}.pkg
      sha256: 869ee1754cbf26aa54b6504a4432b6da55e6b5e4d640f9e8bad624923dca2a12
      file_name: firefox.pkg
  - if: win
    then:
      url: https://ftp.mozilla.org/pub/firefox/releases/${{ version }}/win64/en-US/Firefox%20Setup%20${{ version }}.msi
      sha256: 09f87eb062f1c71d0b72ba3f53c63d71ee6c70a51be4fb805f4d784740465297
      file_name: firefox.msi

build:
  number: 0
  dynamic_linking:
    binary_relocation:
      - bin/firefox
  script:
    file: copy-firefox

requirements:
  build:
    - ${{ compiler("c") }}
    - ${{ compiler("cxx") }}
    - ${{ stdlib("c") }}

tests:
  - requirements:
      run:
        - geckodriver
        - pytest
        - python <3.14
        - selenium >=4
    files:
      recipe:
        - test_selenium.py
    script:
      - pytest -svvv --pythonwarnings=error --tb=long --color=yes

about:
  license: MPL-2.0
  license_file: LICENSE
  summary: Firefox web browser
  homepage: https://www.mozilla.org/en-US/firefox/releases

extra:
  recipe-maintainers:
    - birdsarah
    - ocefpaf
    - bollwyvl
