# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: 137.0.1

package:
  name: firefox
  version: ${{ version }}

source:
  - if: linux and x86_64
    then:
      url: https://ftp.mozilla.org/pub/firefox/releases/${{ version }}/linux-x86_64/en-US/firefox-${{ version }}.tar.xz
      sha256: 0f3150b63b0230aad39270cbd7099d6bb0b24f9295b45c4ae159e20caa52f140
      target_directory: firefox
  - if: osx
    then:
      url: https://ftp.mozilla.org/pub/firefox/releases/${{ version }}/mac/en-US/Firefox%20${{ version }}.pkg
      sha256: 0c51c7d3f0e02bc3d03fcbebe569cf01abd5dde857678603db863f26ef60fa50
      file_name: firefox.pkg
  - if: win
    then:
      url: https://ftp.mozilla.org/pub/firefox/releases/${{ version }}/win64/en-US/Firefox%20Setup%20${{ version }}.msi
      sha256: 178331d524593ea2118935fc8c0fc7107fbe0754f71c401e5b02cc9e2cf55faa
      file_name: firefox.msi

build:
  number: 0
  dynamic_linking:
    binary_relocation:
      - bin/firefox
  script:
    file: copy-firefox

requirements:
  build:
    - ${{ compiler("c") }}
    - ${{ compiler("cxx") }}
    - ${{ stdlib("c") }}

tests:
  - requirements:
      run:
        - geckodriver
        - pytest
        - python
        - selenium >=4
    files:
      recipe:
        - setup.cfg
        - test_selenium.py
    script:
      - pytest -vv --tb=long --color=yes

about:
  license: MPL-2.0
  license_file: LICENSE
  summary: Firefox web browser
  homepage: https://www.mozilla.org/en-US/firefox/releases

extra:
  recipe-maintainers:
    - birdsarah
    - ocefpaf
    - bollwyvl
