# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: "141.0.3"

package:
  name: firefox
  version: ${{ version }}

source:
  - if: linux and x86_64
    then:
      url: https://ftp.mozilla.org/pub/firefox/releases/${{ version }}/linux-x86_64/en-US/firefox-${{ version }}.tar.xz
      sha256: e935dc3b74cf2cb1086e1e0b4a51d18e4d307e71ce6a20db64fe49d09cc78716
      target_directory: firefox
  - if: osx
    then:
      url: https://ftp.mozilla.org/pub/firefox/releases/${{ version }}/mac/en-US/Firefox%20${{ version }}.pkg
      sha256: 14a0b64d8998bcbbd09a458bb16d52d0e157999ff44efa006d1e009e2f3d8d43
      file_name: firefox.pkg
  - if: win
    then:
      url: https://ftp.mozilla.org/pub/firefox/releases/${{ version }}/win64/en-US/Firefox%20Setup%20${{ version }}.msi
      sha256: ad1c68f62f0b2daa6a63f68c79d097d8bfa17b0de707cd65e7d8e7f37dd0eac4
      file_name: firefox.msi

build:
  number: 0
  dynamic_linking:
    binary_relocation:
      - bin/firefox
  script:
    file: copy-firefox

requirements:
  build:
    - ${{ compiler("c") }}
    - ${{ compiler("cxx") }}
    - ${{ stdlib("c") }}

tests:
  - requirements:
      run:
        - geckodriver
        - pytest
        - python
        - selenium >=4
    files:
      recipe: test_selenium.py
    script:
      - pytest -svvv --pythonwarnings=error --tb=long --color=yes

about:
  license: MPL-2.0
  license_file: LICENSE
  summary: Firefox web browser
  homepage: https://www.mozilla.org/en-US/firefox/releases

extra:
  recipe-maintainers:
    - birdsarah
    - ocefpaf
    - bollwyvl
