# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: "147.0.4"

package:
  name: firefox
  version: ${{ version }}

source:
  - if: linux and x86_64
    then:
      url: https://ftp.mozilla.org/pub/firefox/releases/${{ version }}/linux-x86_64/en-US/firefox-${{ version }}.tar.xz
      sha256: fdafe715d3b3ee406e306a27fd91f3e8bdee2fd35c1b3834df6c9134be6265ca
      target_directory: firefox
  - if: osx
    then:
      url: https://ftp.mozilla.org/pub/firefox/releases/${{ version }}/mac/en-US/Firefox%20${{ version }}.pkg
      sha256: 9fe04af0bda04d63287ac3989bd9b5e0245098d66d9b41f86e640c02d103ffe3
      file_name: firefox.pkg
  - if: win
    then:
      url: https://ftp.mozilla.org/pub/firefox/releases/${{ version }}/win64/en-US/Firefox%20Setup%20${{ version }}.msi
      sha256: 648fd8fb1a0389f5f92fdc5778bb8154215339d8552578a5ec3b07336e00b655
      file_name: firefox.msi

build:
  number: 0
  dynamic_linking:
    binary_relocation:
      - bin/firefox
  script:
    file: copy-firefox

requirements:
  build:
    - ${{ compiler("c") }}
    - ${{ compiler("cxx") }}
    - ${{ stdlib("c") }}

tests:
  - requirements:
      run:
        - geckodriver
        - pytest
        - python <3.14
        - selenium >=4
    files:
      recipe:
        - test_selenium.py
    script:
      - pytest -svvv --pythonwarnings=error --tb=long --color=yes

about:
  license: MPL-2.0
  license_file: LICENSE
  summary: Firefox web browser
  homepage: https://www.mozilla.org/en-US/firefox/releases

extra:
  recipe-maintainers:
    - birdsarah
    - ocefpaf
    - bollwyvl
