# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: "140.13.0esr"

package:
  name: firefox
  version: ${{ version }}

source:
  - if: linux and x86_64
    then:
      url: https://ftp.mozilla.org/pub/firefox/releases/${{ version }}/linux-x86_64/en-US/firefox-${{ version }}.tar.xz
      sha256: 866d7e5f94abe93132e02a0db72da32b6e133905fcbea6afa417a96d496021da
      target_directory: firefox
  - if: osx
    then:
      url: https://ftp.mozilla.org/pub/firefox/releases/${{ version }}/mac/en-US/Firefox%20${{ version }}.pkg
      sha256: 96119013f05170ae79efeafbcee63cddc44e2e16c7eb143cdbbacd6f3a775595
      file_name: firefox.pkg
  - if: win
    then:
      url: https://ftp.mozilla.org/pub/firefox/releases/${{ version }}/win64/en-US/Firefox%20Setup%20${{ version }}.msi
      sha256: 084bada1a8c7bd9680ca40ad7841f30c84a816eb0234926a8d753e4994a1ab59
      file_name: firefox.msi

build:
  number: 0
  dynamic_linking:
    binary_relocation:
      - bin/firefox
  script:
    file: copy-firefox

requirements:
  build:
    - ${{ compiler("c") }}
    - ${{ compiler("cxx") }}
    - ${{ stdlib("c") }}

tests:
  - requirements:
      run:
        - geckodriver
        - pytest
        - python <3.14
        - selenium >=4
    files:
      recipe:
        - test_selenium.py
    script:
      - pytest -svvv --pythonwarnings=error --tb=long --color=yes

about:
  license: MPL-2.0
  license_file: LICENSE
  summary: Firefox web browser
  homepage: https://www.mozilla.org/en-US/firefox/releases

extra:
  recipe-maintainers:
    - birdsarah
    - ocefpaf
    - bollwyvl
